from odoo import _

ERROR_MESSAGE_MAPPING = {
    'invalid_param': 'Hubo un error en la carga de los datos. {param}',
    'request_authorization_card': 'Debe pedir autorizacion a su tarjeta',
    '1': 'Solicitar autorización telefónica.',
    '2': 'Idem Anterior',
    '3': 'Verificar parámetros del sistema, código de comercio mal cargado',
    '4': 'Denegada, capturar la tarjeta.',
    '5': 'Denegada.',
    '7': 'Denegada, llamar al Centro de Autorizaciones.',
    '8': 'Ingreso manual incorrecto.',
    '12': 'Verificar el sistema, transacción no reconocida en el sistema.',
    '13': 'Verificar el sistema, error en el formato del campo importe',
    '14': 'Denegada, tarjeta no corresponde.',
    '19': 'Auto approve in ReceivePayment.',
    '25': 'Denegada, registro no encontrado en el archivo de transacciones.',
    '28': 'Momentáneamente el servicio no está disponible. Se debe reintentar en unos segundos.',
    '30': 'Verificar el sistema, error en el formato del mensaje.',
    '31': 'The parameter must be specified when another',
    '38': 'Denegada, excede cantidad de reintentos de PIN',
    '39': 'Ingreso manual incorrecto',
    '43': 'Denegada, retener tarjeta',
    '45': 'Denegada, tarjeta inhibida para operar en cuotas',
    '46': 'Denegada, tarjeta no está vigente aún',
    '47': 'Denegada, tarjeta requiere ingreso de PIN.',
    '48': 'Denegada, excede cantidad máxima de cuotas permitida.',
    '49': 'Verificar el sistema, error en formato de fecha de expiración (vto)',
    '50': 'Entrega supera limite',
    '51': 'Denegada, no posee fondos suficientes.',
    '53': 'Denegada, no existe cuenta asociada.',
    '54': 'Denegada, tarjeta expirada.',
    '55': 'Denegada, código de identificación personal es incorrecto.',
    '56': 'Denegada, emisor no habilitado en el sistema.',
    '57': 'Verificar el sistema, transacción no permitida a dicha tarjeta.',
    '58': 'Verificar el sistema, transacción no permitida a dicha terminal.',
    '61': 'Denegada, excede límite remanente de la tarjeta.',
    '65': 'Denegada, excede límite remanente de la tarjeta',
    '76': 'Solicitar autorización telefónica,',
    '77': 'Denegada, cantidad de cuotas inválida para el plan seleccionado.',
    '89': 'Denegada, número de terminal no habilitado por el Emisor.',
    '91': 'Solicitar autorización telefónica,',
    '94': 'Denegada. Error en mensaje. Envíe nuevamente la transacción incrementando en uno el system trace de la misma',
    '95': 'Diferencias en la conciliación del cierre, envíe Batch Upload.',
    '96': 'Mal funcionamiento del sistema. Solicitar autorización telefónica.',
    '97': 'Error en sistema host',
    '98': 'Deben imprimir la información Suministrada en el Campo ISO 63.',
    '480': 'Procesamiento del Decision Manager',
    '481': 'Procesamiento del Decision Manager',
    '101': 'Campos obligatorios incompletos',
    '102': 'Validación de campos',
    '202': 'Validación de campos',
    '231': 'Validación de campos',
    '150': 'Servicio de CyberSource no disponible',
    '151': 'Servicio de CyberSource no disponible',
    '152': 'Servicio de CyberSource no disponible',
    '153': 'Servicio de CyberSource no disponible por Decidir',
    '10101': 'Se requiere la ciudad del cliente (Bill To City)',
    '10102': 'Se requiere el país del cliente (Bill To Country)',
    '10103': 'Se requiere el ID del cliente (Bill To CustomerID)',
    '10104': 'Se requiere el correo electrónico del cliente (Bill To Email)',
    '10105': 'Se requiere el nombre del cliente (Bill To First Name)',
    '10106': 'Se requiere la dirección IP del cliente (Bill To IP Address)',
    '10107': 'Se requiere el apellido del cliente (Bill To Last Name)',
    '10108': 'Se requiere el número de teléfono del cliente (Bill To Phone Number)',
    '10109': 'Se requiere el código postal del cliente (Bill To Postal Code)',
    '10110': 'Se requiere la provincia del cliente (Bill To State)',
    '10111': 'Se requiere la dirección del cliente (Bill To Street1)',
    '10130': 'El elemento en el índice 0 debe incluir un valor de código de producto válido.',
    '10132': 'El elemento en el índice 0 debe incluir un valor de nombre de producto válido.',
    '10133': 'El elemento en el índice 0 debe incluir un valor de SKU de producto válido.',
    '10134': 'El elemento en el índice 0 debe incluir un valor de cantidad válido.',
    '10135': 'El elemento en el índice 0 debe incluir un valor de monto total válido.',
    '10136': 'El elemento en el índice 0 debe incluir un valor de precio unitario válido.',
    '10140': 'Se requiere la moneda de compra (Purchase Currency)',
    '10141': 'Se requiere el monto total de compra (Purchase Grand Total Amount)',
    '10150': 'Se requiere el ID de huella digital del dispositivo en el mensaje de solicitud (Request Message DeviceFingerprintID)',
    '10151': 'Se requiere la información de huella digital cruda del dispositivo en el mensaje de solicitud (Request Message DeviceFingerprintRaw)',
    '10152': 'Se requiere el ID del comerciante en el mensaje de solicitud (Request Message MerchantId)',
    '10153': 'Se requiere el código de referencia del comerciante en el mensaje de solicitud (Request Message MerchantReferenceCode)',
    '10160': 'Se requiere la ciudad de envío (Ship To City)',
    '10161': 'Se requiere el país de envío (Ship To Country)',
    '10162': 'Se requiere el correo electrónico de envío (Ship To Email)',
    '10163': 'Se requiere el nombre de envío (Ship To First Name)',
    '10164': 'Se requiere el apellido de envío (Ship To Last Name)',
    '10165': 'Se requiere el número de teléfono de envío (Ship To Phone Number)',
    '10166': 'Se requiere el código postal de envío (Ship To Postal Code)',
    '10167': 'Se requiere el estado de envío (Ship To State)',
    '10168': 'Se requiere la dirección de envío (Ship To Street1)',
    '10170': 'Se requiere CompleteRoute de DecisionManagerTravelData',
    '10171': 'Se requiere JourneyType de DecisionManagerTravelData',
    '10172': 'Se requiere departureDateTime de DecisionManagerTravelData',
    '10180': 'Se requiere NumberOfPassengers de AirlineData',
    '10302': 'Código ISO de país de cliente (BillTo Country) no válido',
    '10304': 'Correo electrónico de cliente (BillTo Email) no válido',
    '10305': 'Nombre de cliente (BillTo FirstName) no válido',
    '10306': 'Dirección IP de cliente (BillTo IP Address) no válida',
    '10307': 'Apellido de cliente (BillTo LastName) no válido',
    '10309': 'Código postal de cliente (BillTo PostalCode) no válido',
    '10310': 'Provincia de cliente (BillTo State) no válida',
    '10320': 'Número de cuenta de tarjeta no válido',
    '10321': 'Tipo de tarjeta no válido',
    '10322': 'Mes de vencimiento de tarjeta no válido',
    '10323': 'Año de vencimiento de tarjeta no válido',
    '10334': 'El elemento en el índice 0 debe incluir un valor de cantidad válido.',
    '10335': 'El elemento en el índice 0 debe incluir un valor de monto total válido.',
    '10336': 'El elemento en el índice 0 debe incluir un valor de precio unitario válido.',
    '10340': 'Moneda de PurchaseTotals no válida',
    '10341': 'Gran total de PurchaseTotals no válido',
    '10360': 'Ciudad de envío (Ship To City) no válida',
    '10361': 'País de envío (Ship To Country) no válido',
    '10362': 'Correo electrónico de envío (Ship To Email) no válido',
    '10363': 'Nombre de envío (Ship To First Name) no válido',
    '10364': 'Apellido de envío (Ship To Last Name) no válido',
    '10365': 'Número de teléfono de envío (Ship To Phone Number) no válido',
    '10366': 'Código postal de envío (Ship To Postal Code) no válido',
    '10367': 'Estado de envío (Ship To State) no válido',
    '10368': 'Dirección de envío (Ship To Street1) no válida',
    '10370': 'CompleteRoute de DecisionManagerTravelData no válido',
    '10371': 'JourneyType de DecisionManagerTravelData no válido',
    '10372': 'departureDateTime de DecisionManagerTravelData no válido',
    '10380': 'NumberOfPassengers de AirlineData no válido',
    '10501': 'Se requiere el número de afiliación del comerciante (MDD1)',
    '10502': 'Se requiere el nombre del comerciante (MDD2)',
    '10503': 'Se requiere el sector comercial (MDD3)',
    '10517': 'Se requiere el código de reserva (PNR) en los campos adicionales de viaje (MDD17)',
    '10518': 'Se requiere la reserva de terceros en los campos adicionales de viaje (MDD18)',
    '10528': 'Se requiere el tipo de servicio en los campos adicionales de servicios (MDD28)',
    '10532': 'Se requiere el tipo de entrega en los campos adicionales de bienes digitales (MDD32)',
    '10533': 'Se requiere el número de días para el evento en los campos adicionales de boletos (MDD33)',
    '10534': 'Se requiere el tipo de entrega en los campos adicionales de boletos (MDD34)',
    '10701': 'Número de afiliación del comercial(MDD1)',
    '10703': 'Número de afiliación del comerciante no válido (MDD3)',
    '10718': 'Reserva de terceros no válida en campos adicionales de viaje (MDD18)',
    '10733': 'Número de días para el evento no válido en campos adicionales de boletos (MDD33)',
    '10310': 'La Provincia del cliente no es valida.',
    '00': 'El telefono del cliente no tiene el tamaño correcto.',
}
PAYWAY_INVALID_PARAMS = {
    'card_number': 'El numero de Tarjeta es incorrecto.',
    'bin': 'El numero de Tarjeta invalido es invalido',
}
PAYWAY_METHODS = [('1', 'Visa'),
                ('8', 'Diners Club'),
                ('23', 'Tarjeta Shopping'),
                ('24', 'Tarjeta Naranja'),
                ('25', 'PagoFacil'),
                ('26', 'RapiPago'),
                ('29', 'Italcred'),
                ('30', 'ArgenCard'),
                ('34', 'CoopePlus'),
                ('37', 'Nexo'),
                ('38', 'Credimás'),
                ('39', 'Tarjeta Nevada'),
                ('42', 'Nativa'),
                ('43', 'Tarjeta Cencosud'),
                ('44', 'Tarjeta Carrefour / Cetelem'),
                ('45', 'Tarjeta PymeNacion'),
                ('48', 'Caja de Pagos'),
                ('50', 'BBPS'),
                ('51', 'Cobro Express'),
                ('52', 'Qida'),
                ('54', 'Grupar'),
                ('55', 'Patagonia 365'),
                ('56', 'Tarjeta Club Día'),
                ('59', 'Tuya'),
                ('60', 'Distribution'),
                ('61', 'Tarjeta La Anónima'),
                ('62', 'CrediGuia'),
                ('63', 'Cabal Prisma'),
                ('64', 'Tarjeta SOL'),
                ('65', 'American Express'),
                ('103', 'Favacard'),
                ('104', 'MasterCard Prisma'),
                ('109', 'Nativa Prisma'),
                ('111', 'American Express Prisma'),
                ('31', 'Visa Débito'),
                ('105', 'MasterCard Debit Prisma'),
                ('106', 'Maestro Prisma'),
                ('108', 'Cabal Débito Prisma')
                ]

PROD_BASE_API_URL = 'https://live.decidir.com/api/v2'
TEST_BASE_API_URL = 'https://developers.decidir.com/api/v2'

SUPPORTED_CURRENCIES = [
    'ARS',  # Argentinian Peso
    'USD',  # Argentinian Peso
]

DEFAULT_PAYMENT_METHODS_CODES = [
    # Primary payment methods.
    'payway',
    # Brand payment methods.
    'visa',
    'mastercard',
    'naranja',
    'nativa',
    'amex'
]

PAYMENT_METHODS_MAPPING = {
    'payway': 'debit_card,credit_card,prepaid_card',
}

# Creo que esto se va??? ver
TRANSACTION_STATUS_MAPPING = {
    'pending': ('pending', 'in_process', 'in_mediation', 'authorized'),
    'done': ('approved', 'refunded'),
    'canceled': ('cancelled', 'null'),
    'error': ('rejected'),
}
